const Location =  {
  MOSCOW: 'Moscow',
  PETERSBURG: 'Saint Petersburg',
  NOVOSIBIRSK: 'Novosibirsk',
  YEKATERINBURG: 'Yekaterinburg',
  KAZAN: 'Kazan',
}

export const data = [{
  id: 0,
  location: Location.MOSCOW,
  price: 10000,
  text: 'Shelter-Hotels',
  img: '',
}, {
  id: 1,
  location: Location.MOSCOW,
  price: 4000,
  text: 'Ibis Moscow Kievskaya',
  img: '',
}, {
  id: 2,
  location: Location.MOSCOW,
  price: 20000,
  text: 'Radisson Slavyanskaya Hotel',
  img: '',
}, {
  id: 3,
  location: Location.MOSCOW,
  price: 5500,
  text: 'Myhotel24 Korovinskoe',
  img: '',
}, {
  id: 4,
  location: Location.MOSCOW,
  price: 16110,
  text: 'Moss Boutique Hotel',
  img: '',
}, {
  id: 5,
  location: Location.PETERSBURG,
  price: 2400,
  text: 'Piter Palace Gallery',
  img: '',
}, {
  id: 6,
  location: Location.PETERSBURG,
  price: 2000,
  text: 'Inn Ivan da Maria',
  img: '',
}, {
  id: 7,
  location: Location.PETERSBURG,
  price: 1800,
  text: 'Nouvelle Europe',
  img: '',
}, {
  id: 8,
  location: Location.PETERSBURG,
  price: 3000,
  text: 'Capsule Hotel de Lux ApraxInn',
  img: '',
}, {
  id: 9,
  location: Location.NOVOSIBIRSK,
  price: 2300,
  text: 'Why Not Hostel',
  img: '',
}, {
  id: 10,
  location: Location.NOVOSIBIRSK,
  price: 3000,
  text: 'Siberia.Life',
  img: '',
}, {
  id: 11,
  location: Location.NOVOSIBIRSK,
  price: 4500,
  text: 'Marins Park Hotel',
  img: '',
}, {
  id: 12,
  location: Location.NOVOSIBIRSK,
  price: 30000,
  text: 'Park Inn by Radisson',
  img: '',
}, {
  id: 13,
  location: Location.YEKATERINBURG,
  price: 30000,
  text: 'Novotel',
  img: '',
}, {
  id: 14,
  location: Location.YEKATERINBURG,
  price: 2500,
  text: 'Story Hostel',
  img: '',
}, {
  id: 15,
  location: Location.YEKATERINBURG,
  price: 11000,
  text: 'Emerald',
  img: '',
}, {
  id: 16,
  location: Location.KAZAN,
  price: 1700,
  text: 'Ibis',
  img: '',
}, {
  id: 17,
  location: Location.KAZAN,
  price: 30000,
  text: 'Courtyard by Marriott Kazan Kremlin',
  img: '',
}, {
  id: 18,
  location: Location.KAZAN,
  price: 11000,
  text: 'DoubleTree',
  img: '',
}, {
  id: 19,
  location: Location.KAZAN,
  price: 7450,
  text: 'Bilyar Palace Hotel',
  img: '',
}]